// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpwmLRlAb1UuyvbZEe26nBz4omEBWyYLA',
    appId: '1:406145459213:web:598be7649613981348e144',
    messagingSenderId: '406145459213',
    projectId: 'crudjose-fa2bd',
    authDomain: 'crudjose-fa2bd.firebaseapp.com',
    storageBucket: 'crudjose-fa2bd.appspot.com',
    measurementId: 'G-KY7VF7GML1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyConRHp-HCMK5MjiwhHh_7bbGZx8oFeI18',
    appId: '1:406145459213:android:cf69f203e459d52248e144',
    messagingSenderId: '406145459213',
    projectId: 'crudjose-fa2bd',
    storageBucket: 'crudjose-fa2bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuYsqfOQcCKnNoDKtiDRHWxsUl17ZuZuA',
    appId: '1:406145459213:ios:f5739c9b3667344d48e144',
    messagingSenderId: '406145459213',
    projectId: 'crudjose-fa2bd',
    storageBucket: 'crudjose-fa2bd.appspot.com',
    iosClientId: '406145459213-458i12inaf4sg06haarns54seiinalli.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crudfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuYsqfOQcCKnNoDKtiDRHWxsUl17ZuZuA',
    appId: '1:406145459213:ios:a706a9bd08d8d38c48e144',
    messagingSenderId: '406145459213',
    projectId: 'crudjose-fa2bd',
    storageBucket: 'crudjose-fa2bd.appspot.com',
    iosClientId: '406145459213-oukngjlmkkkau5aq4m8e1cc539jeaoqo.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crudfire.RunnerTests',
  );
}
